# Generated by Django 4.2.10 on 2024-02-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('City', '0001_initial'),
        ('BloodCenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcenter',
            name='cityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='City.city'),
        ),
    ]
