# Generated by Django 4.2.10 on 2024-02-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
        ('BloodDonation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.person'),
        ),
    ]
